# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app/client
WORKDIR /yolo/client

# Copy the package.json and package-lock.json files to the container
COPY client/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY client/ ./

# Expose port 3000 for the client to listen on
EXPOSE 3000

# Start the client application
CMD ["npm", "start"]
