version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/yolo/backend
    restart: always

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/yolo/client
    restart: always
